# Generated by Django 5.1 on 2024-08-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('soil_moisture', models.FloatField()),
                ('soil_temperature', models.FloatField()),
                ('nitrogen_content', models.IntegerField()),
                ('phosphorus_content', models.IntegerField()),
                ('potassium_content', models.IntegerField()),
                ('soil_ph', models.FloatField()),
            ],
        ),
    ]
